---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: load-balancer-controller
  namespace: kube-system
spec:
  releaseName: load-balancer-controller
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: 1.6.2
      sourceRef:
        kind: HelmRepository
        name: load-balancer-controller
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    fullnameOverride: load-balancer-controller
    replicaCount: 1
    serviceAccount:
      create: true
      name: aws-load-balancer-controller
    image:
      tag: v2.6.2
