---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: policy-reporter
  namespace: policy-reporter
spec:
  releaseName: policy-reporter
  chart:
    spec:
      chart: policy-reporter
      version: 2.21.5
      sourceRef:
        kind: HelmRepository
        name: policy-reporter
        namespace: flux-system
  interval: 30m0s
  install:
    remediation:
      retries: 3
---
