{
 "title": "Karpenter General",
 "description": "Display all useful Karpenter metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "provisioner",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable, provisioner)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster CPU Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_nodes_total_pod_requests{provisioner_name=\"$provisioner\",resource_type=\"cpu\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Cluster Memory Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_nodes_total_pod_requests{provisioner_name=\"$provisioner\",resource_type=\"memory\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Total number of pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_pods_state{provisioner=\"$provisioner\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster CPU Reservation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_nodes_total_pod_requests{provisioner_name=\"$provisioner\",resource_type=\"cpu\"}) / sum(karpenter_nodes_allocatable{provisioner_name=\"$provisioner\", resource_type=\"cpu\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Cluster Memory Reservation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_nodes_total_pod_requests{provisioner_name=\"$provisioner\",resource_type=\"memory\"}) / sum(karpenter_nodes_allocatable{provisioner_name=\"$provisioner\", resource_type=\"memory\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Node AZ Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(karpenter_nodes_total_pod_requests{provisioner_name=\"$provisioner\",resource_type=\"pods\"}) by (zone)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod AZ Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_pods_state{provisioner=\"$provisioner\"}) by (zone)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster CPU",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(karpenter_nodes_allocatable{provisioner_name=\"$provisioner\", resource_type=\"cpu\"})",
       "legendFormat": "Allocatable"
      },
      {
       "expr": "sum(karpenter_nodes_total_pod_requests{provisioner_name=\"$provisioner\",resource_type=\"cpu\"})",
       "legendFormat": "Requested"
      }
     ]
    },
    {
     "title": "Cluster Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(karpenter_nodes_allocatable{provisioner_name=\"$provisioner\", resource_type=\"memory\"})",
       "legendFormat": "Allocatable"
      },
      {
       "expr": "sum(karpenter_nodes_total_pod_requests{provisioner_name=\"$provisioner\",resource_type=\"memory\"})",
       "legendFormat": "Requested"
      }
     ]
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Activity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "idelta(karpenter_nodes_created{provisioner=\"$provisioner\"}[$__rate_interval])",
       "legendFormat": "created"
      },
      {
       "expr": "idelta(karpenter_nodes_terminated{provisioner=\"$provisioner\"}[$__rate_interval])",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Node AZ Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "count(karpenter_nodes_total_pod_requests{provisioner_name=\"$provisioner\",resource_type=\"pods\"}) by (zone)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Node CPU Reservation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "karpenter_nodes_total_pod_requests{provisioner_name=\"$provisioner\",resource_type=\"cpu\"} / karpenter_nodes_allocatable{provisioner_name=\"$provisioner\",resource_type=\"cpu\"}",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Node Memory Reservation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "karpenter_nodes_total_pod_requests{provisioner_name=\"$provisioner\",resource_type=\"memory\"} / karpenter_nodes_allocatable{provisioner_name=\"$provisioner\", resource_type=\"memory\"}",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Interruption Messages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "idelta(karpenter_interruption_received_messages[1m])",
       "legendFormat": "{{message_type}}"
      }
     ]
    },
    {
     "title": "Deleted Interruption Messages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "expr": "sum(idelta(karpenter_interruption_deleted_messages[1m]))",
       "legendFormat": "Number of messages deleted"
      }
     ]
    }
   ]
  },
  { "title": "Pods by Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Number of pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(karpenter_pods_state{provisioner=\"$provisioner\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pod AZ Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(karpenter_pods_state{provisioner=\"$provisioner\"}) by (zone)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Skew ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "max(sum(karpenter_pods_state{provisioner=\"$provisioner\"}) by (zone)) - min(sum(karpenter_pods_state{provisioner=\"$provisioner\"}) by (zone))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}