---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-private
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: external-dns-private
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns-private
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: eu.gcr.io/k8s-artifacts-prod/external-dns/external-dns:v0.13.4
        args:
        - --source=service
        - --source=ingress
        - --provider=aws
        - --annotation-filter=private-hosted-zone-record in (true, True, TRUE)
        - --aws-zone-type=private
        - --registry=txt
        resources:
          requests:
            memory: 100Mi
            cpu: 50m
          limits:
            memory: 100Mi
            cpu: 50m
      securityContext:
        fsGroup: 65534
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-public
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: external-dns-public
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns-public
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: eu.gcr.io/k8s-artifacts-prod/external-dns/external-dns:v0.13.4
        args:
        - --source=service
        - --source=ingress
        - --provider=aws
        - --annotation-filter=public-hosted-zone-record in (true, True, TRUE)
        - --aws-zone-type=public
        - --registry=txt
        resources:
          requests:
            memory: 100Mi
            cpu: 50m
          limits:
            memory: 100Mi
            cpu: 50m
      securityContext:
        fsGroup: 65534
---
